### PR TITLE
Release 5.1.0

### PR DESCRIPTION
**Pull request by defunctl**
### Changelog

- [UPDATED]: global docker-compose.yml to add a fixed version for the Nginx proxy image (0.9.0).
- [ADDED]: Docker health checking to the MariaDB container (`docker ps` will show the health status of the container)
- [ADDED]: `so bootstrap --multisite` to install WP core as multisite
- [FIXED]: Building frontend assets with `so bootstrap` or `so create` due to yarn missing for specific node versions.
- [FIXED]: Wait for health check to complete for the MariaDB container before trying to create new databases during `so bootstrap/so create`
- [FIXED]: `--only-new` error showing up when running a command that doesn't exist.
- [ADDED]: CLI spinner for longer running processes like building the frontend

### Testing Instructions

- Check out this branch, `composer install` and verify `sodev` or `./so` shows version `5.1.0`.
- Run `sodev global:stop-all` to automatically run the latest migration to copy the new global docker-compose.yml (should see `★ Updating global docker-compose.yml...`) You should have a backup docker-compose.yml in `~/.config/squareone/global` and the new version should contain a healthcheck item the `mysql` section:
```
    healthcheck:
      test: mysqladmin ping -h mysql -u root --password=$$MYSQL_PASSWORD
      timeout: 3s
      retries: 20
```
- Remove the node version being used by SquareOne to mimic a fresh install: `nvm uninstall v14.15.1`.
- Run `sodev create` and the process should properly build the frontend and create the new databases for the project.

### CODE REVIEW

**Comment by nickpelton** [comment]
Awesome! Have some time Thurs to test.

**Comment by nickpelton** [comment]
Followed testing instructions and it failed. I have a particularly large DB so it can sometimes take 3-5m to start up. Maybe the timeout should be a bit longer?

```
Project started: https://test510.tribe
Starting docker containers: ✔
Error: `Unknown database 'tribe_test510'`
Can’t select database
We were able to connect to the database server (which means your username and password is okay) but not able to select the `tribe_test510` database.

Are you sure it exists?
Does the user `root` have permission to use the `tribe_test510` database?
On some systems the name of your database is prefixed with your username, so it would be like `username_tribe_test510`. Could that be the problem?

If you don’t know how to set up a database you should contact your host. If all else fails you may find help at the WordPress Support Forums. `Unknown database 'tribe_test510'`
Error: `Unknown database 'tribe_test510'`
Can’t select database
We were able to connect to the database server (which means your username and password is okay) but not able to select the `tribe_test510` database.

Are you sure it exists?
Does the user `root` have permission to use the `tribe_test510` database?
On some systems the name of your database is prefixed with your username, so it would be like `username_tribe_test510`. Could that be the problem?

If you don’t know how to set up a database you should contact your host. If all else fails you may find help at the WordPress Support Forums. `Unknown database 'tribe_test510'`
Installing WordPress: ✔
Done! Opening https://test510.tribe in your default browser
```

**Comment by defunctl** [comment]
> Followed testing instructions and it failed. I have a particularly large DB so it can sometimes take 3-5m to start up. Maybe the timeout should be a bit longer?
> 
> ```
> Project started: https://test510.tribe
> Starting docker containers: ✔
> Error: `Unknown database 'tribe_test510'`
> Can’t select database
> We were able to connect to the database server (which means your username and password is okay) but not able to select the `tribe_test510` database.
> 
> Are you sure it exists?
> Does the user `root` have permission to use the `tribe_test510` database?
> On some systems the name of your database is prefixed with your username, so it would be like `username_tribe_test510`. Could that be the problem?
> 
> If you don’t know how to set up a database you should contact your host. If all else fails you may find help at the WordPress Support Forums. `Unknown database 'tribe_test510'`
> Error: `Unknown database 'tribe_test510'`
> Can’t select database
> We were able to connect to the database server (which means your username and password is okay) but not able to select the `tribe_test510` database.
> 
> Are you sure it exists?
> Does the user `root` have permission to use the `tribe_test510` database?
> On some systems the name of your database is prefixed with your username, so it would be like `username_tribe_test510`. Could that be the problem?
> 
> If you don’t know how to set up a database you should contact your host. If all else fails you may find help at the WordPress Support Forums. `Unknown database 'tribe_test510'`
> Installing WordPress: ✔
> Done! Opening https://test510.tribe in your default browser
> ```

@nickpelton Did you see this waiting message? It should be waiting until your database is accessible, so if that takes 3-5m it should have sat there for that long:

image

**Comment by nickpelton** [comment]
It worked if I started the global containers first. So pretty sure the healthcheck timeout should just be bumped to 5+ mins.

**Comment by defunctl** [comment]
@nickpelton can you give this another test, please.

This update also adds env vars to customize these if really required (besides the retires, which needs to be an int and all env vars are strings)

### Testing Steps:

1. `so global:stop-all`
2. `git pull`
3. Since the migration already ran that copies the updated dc.yml file, can you manually copy the updated `storage/global/docker-compose.yml` to `~/.config/squareone/global/docker-compose.yml`
3. `so create <whatever>`

**Review by nickpelton — APPROVED** [review]
🚀

**Pull request merged**
