### PR TITLE
Issue #12

### PR DESCRIPTION
**Pull request by rwrobe**
String coerced the getLinuxFlavorand added Zorin to the OS list

### CODE REVIEW

**Comment by defunctl** [comment]
Whoops, wrote that in the issue and not the PR:

Thanks for this Rob! Please add the proper paths to the config file here: https://github.com/moderntribe/square1-global-docker/blob/master/config/squareone.yml#L57

and

https://github.com/moderntribe/square1-global-docker/blob/master/config/squareone.yml#L74

**Comment by rwrobe** [comment]
@defunctl please check it out again, added Zorin as a Debian-based distro

**Comment by defunctl** [comment]
@rwrobe Thanks! I ended up adding this in my tests branch: https://github.com/moderntribe/square1-global-docker/commit/c5382162b7f0a9c1cb91ee9316de3f5613739775

So we can close this unless it's something you'd like in a minor release sooner :)

**Comment by rwrobe** [comment]
Thanks, no rush! Should I close this out then?

**Comment by defunctl** [comment]
Should be fixed in https://github.com/moderntribe/square1-global-docker/pull/30

**Pull request closed without merging**
